import CryptoKit
import Foundation
import XCTest
@testable import AgentWearLinkOpenClaw

private actor MockOpenClawWebSocket: OpenClawWebSocket {
    private var inbound: [String]
    private(set) var outbound: [String] = []
    private(set) var didConnect = false
    private(set) var didClose = false

    init(inbound: [String]) {
        self.inbound = inbound
    }

    func connect() async { didConnect = true }

    func send(text: String) async throws {
        outbound.append(text)
    }

    func receive() async throws -> String {
        guard !inbound.isEmpty else { throw AWLOpenClawError.disconnected }
        return inbound.removeFirst()
    }

    func close() async { didClose = true }

    func sent() -> [String] { outbound }
    func closed() -> Bool { didClose }
}

private actor StalledHandshakeSocket: OpenClawWebSocket {
    private let emitChallengeBeforeStall: Bool
    private var receiveCount = 0
    private var sentFrames: [String] = []
    private var receiveWaiter: CheckedContinuation<String, Error>?
    private var blockedReceive = false
    private var blockedReceiveWaiter: CheckedContinuation<Void, Never>?
    private var didClose = false

    init(emitChallengeBeforeStall: Bool) {
        self.emitChallengeBeforeStall = emitChallengeBeforeStall
    }

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        if emitChallengeBeforeStall && receiveCount == 0 {
            receiveCount += 1
            return #"{"type":"event","event":"connect.challenge","payload":{"nonce":"timeout-test","ts":1737264000000}}"#
        }

        receiveCount += 1
        blockedReceive = true
        blockedReceiveWaiter?.resume()
        blockedReceiveWaiter = nil

        return try await withCheckedThrowingContinuation { continuation in
            receiveWaiter = continuation
        }
    }

    func close() async {
        didClose = true
        if let receiveWaiter {
            self.receiveWaiter = nil
            receiveWaiter.resume(throwing: AWLOpenClawError.disconnected)
        }
    }

    func waitUntilReceiveIsBlocked() async {
        if blockedReceive { return }
        await withCheckedContinuation { continuation in
            blockedReceiveWaiter = continuation
        }
    }

    func closed() -> Bool { didClose }
    func sentCount() -> Int { sentFrames.count }
}

private final class HandshakeProgressRecorder: @unchecked Sendable {
    private let lock = NSLock()
    private var phases: [String] = []

    func record(_ phase: OpenClawHandshakeProgress) {
        lock.lock()
        defer { lock.unlock() }
        phases.append(phase.rawValue)
    }

    func snapshot() -> [String] {
        lock.lock()
        defer { lock.unlock() }
        return phases
    }
}

final class OpenClawGatewayConnectionTests: XCTestCase {
    private func makeAssembler() -> OpenClawConnectAssembler {
        OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore()
            ),
            credentialStore: InMemoryOpenClawDeviceCredentialStore()
        )
    }

    func testChallengeConnectHelloHandshake() async throws {
        let challenge = #"{"type":"event","event":"connect.challenge","payload":{"nonce":"abc","ts":1737264000000}}"#
        let hello = #"{"type":"res","id":"REQUEST_ID","ok":true,"payload":{"type":"hello-ok","protocol":4,"server":{"version":"2026.10","connId":"c1"},"features":{"methods":["health"],"events":["agent"]},"auth":{"role":"operator","scopes":["operator.read","operator.write"]},"policy":{"maxPayload":26214400,"maxBufferedBytes":52428800,"tickIntervalMs":15000}}}"#

        let socket = MockOpenClawWebSocket(inbound: [challenge])
        await socket.connect()

        // Request IDs are generated by the connection, so use a second mock
        // that rewrites the response after observing the outbound connect.
        let adaptive = AdaptiveHandshakeSocket(challenge: challenge)
        let recorder = HandshakeProgressRecorder()
        let connection = OpenClawGatewayConnection(
            socket: adaptive,
            assembler: makeAssembler(),
            progress: { recorder.record($0) }
        )

        let result = try await connection.connect(
            appVersion: "0.1.0",
            credentials: .init(token: "secret")
        )

        XCTAssertEqual(result.protocolVersion, 4)
        XCTAssertEqual(result.server.connId, "c1")
        let sentCount = await adaptive.sentCount()
        XCTAssertEqual(sentCount, 1)
        XCTAssertEqual(recorder.snapshot(), [
            "socket-opened", "challenge-received", "assemble-started",
            "assemble-complete", "connect-sending", "connect-sent",
            "response-received",
        ])
    }


    func testBootstrapHandshakeSendsAndSignsBootstrapToken() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: InMemoryOpenClawDeviceCredentialStore()
        )
        let challenge = #"{"type":"event","event":"connect.challenge","payload":{"nonce":"bootstrap-nonce","ts":1737264000000}}"#
        let socket = AdaptiveHandshakeSocket(challenge: challenge)
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: assembler
        )

        _ = try await connection.connect(
            appVersion: "0.1.0",
            scopes: ["operator.read"],
            credentials: .init(bootstrapToken: "bootstrap-secret")
        )

        let frames = await socket.sentFramesSnapshot()
        let frame = try XCTUnwrap(frames.first)
        let data = try XCTUnwrap(frame.data(using: .utf8))
        let json = try XCTUnwrap(
            try JSONSerialization.jsonObject(with: data) as? [String: Any]
        )
        let params = try XCTUnwrap(json["params"] as? [String: Any])
        let auth = try XCTUnwrap(params["auth"] as? [String: Any])
        XCTAssertEqual(auth["bootstrapToken"] as? String, "bootstrap-secret")
        XCTAssertNil(auth["token"])
        XCTAssertNil(auth["deviceToken"])

        let device = try XCTUnwrap(params["device"] as? [String: Any])
        let signatureText = try XCTUnwrap(device["signature"] as? String)
        let signedAt = try XCTUnwrap(device["signedAt"] as? Int64)
        let nonce = try XCTUnwrap(device["nonce"] as? String)

        var encodedSignature = signatureText
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        encodedSignature += String(
            repeating: "=",
            count: (4 - encodedSignature.count % 4) % 4
        )
        let signature = try XCTUnwrap(Data(base64Encoded: encodedSignature))

        let client = try XCTUnwrap(params["client"] as? [String: Any])
        let payload = OpenClawDeviceProofBuilder().buildPayloadV3(
            deviceID: try identity.deviceID,
            clientID: try XCTUnwrap(client["id"] as? String),
            clientMode: try XCTUnwrap(client["mode"] as? String),
            role: try XCTUnwrap(params["role"] as? String),
            scopes: try XCTUnwrap(params["scopes"] as? [String]),
            token: "bootstrap-secret",
            nonce: nonce,
            signedAt: signedAt,
            platform: try XCTUnwrap(client["platform"] as? String),
            deviceFamily: try XCTUnwrap(client["deviceFamily"] as? String)
        )
        let publicKey = try Curve25519.Signing.PublicKey(
            rawRepresentation: identity.publicKeyRaw
        )
        XCTAssertTrue(publicKey.isValidSignature(signature, for: payload))
    }

    func testChallengeWaitTimesOutAndClosesSocket() async {
        let socket = StalledHandshakeSocket(emitChallengeBeforeStall: false)
        let state = OpenClawGatewayState()
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler(),
            state: state,
            handshakeTimeout: .milliseconds(10)
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected challenge timeout")
        } catch let error as OpenClawHandshakeError {
            XCTAssertEqual(error, .challengeTimeout)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let closed = await socket.closed()
        let connectionState = await state.connectionState
        XCTAssertTrue(closed)
        XCTAssertEqual(connectionState, .disconnected)
    }

    func testHelloWaitTimesOutAfterConnectRequestAndClosesSocket() async {
        let socket = StalledHandshakeSocket(emitChallengeBeforeStall: true)
        let state = OpenClawGatewayState()
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler(),
            state: state,
            handshakeTimeout: .milliseconds(10)
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected hello timeout")
        } catch let error as OpenClawHandshakeError {
            XCTAssertEqual(error, .helloTimeout)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let sentCount = await socket.sentCount()
        let closed = await socket.closed()
        let connectionState = await state.connectionState
        XCTAssertEqual(sentCount, 1)
        XCTAssertTrue(closed)
        XCTAssertEqual(connectionState, .disconnected)
    }

    func testCancellationDuringHandshakeClosesSocketAndCannotPublishReady() async {
        let socket = StalledHandshakeSocket(emitChallengeBeforeStall: false)
        let state = OpenClawGatewayState()
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler(),
            state: state,
            handshakeTimeout: .seconds(30)
        )

        let connectTask = Task {
            try await connection.connect(appVersion: "0.1.0")
        }

        await socket.waitUntilReceiveIsBlocked()
        connectTask.cancel()

        do {
            _ = try await connectTask.value
            XCTFail("Expected cancellation")
        } catch is CancellationError {
            // Expected.
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let closed = await socket.closed()
        let connectionState = await state.connectionState
        XCTAssertTrue(closed)
        XCTAssertEqual(connectionState, .disconnected)
    }

    func testMissingChallengeClosesSocket() async {
        let socket = MockOpenClawWebSocket(
            inbound: [#"{"type":"event","event":"tick","payload":{}}"#]
        )
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler()
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected handshake failure")
        } catch let error as OpenClawHandshakeError {
            XCTAssertEqual(error, .challengeRequired)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let didClose = await socket.closed()
        XCTAssertTrue(didClose)
    }

    func testGatewayErrorPreservesBoundedRetryAfterGuidance() async {
        let socket = RejectingHandshakeSocket(retryAfterMs: 12_345)
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler()
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected Gateway rejection")
        } catch let error as AWLOpenClawError {
            XCTAssertEqual(
                error,
                .gateway(
                    code: "BUSY",
                    retryable: true,
                    retryAfterMilliseconds: 12_345
                )
            )
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }

    func testGatewayErrorDropsPathologicalRetryAfterGuidance() async {
        let socket = RejectingHandshakeSocket(retryAfterMs: 300_001)
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler()
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected Gateway rejection")
        } catch let error as AWLOpenClawError {
            XCTAssertEqual(
                error,
                .gateway(
                    code: "BUSY",
                    retryable: true,
                    retryAfterMilliseconds: nil
                )
            )
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }

    func testPairingRequiredInvalidatesStoredCredential() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let deviceID = try identity.deviceID
        let credentialStore = InMemoryOpenClawDeviceCredentialStore()
        try await credentialStore.save(
            .init(
                deviceID: deviceID,
                role: "operator",
                scopes: ["operator.read"],
                token: "stored"
            )
        )
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: credentialStore
        )
        let connection = OpenClawGatewayConnection(
            socket: PairingRequiredHandshakeSocket(),
            assembler: assembler
        )

        do {
            _ = try await connection.connect(
                appVersion: "0.1.0",
                credentials: .init(bootstrapToken: "bootstrap")
            )
            XCTFail("Expected pairing-required rejection")
        } catch let error as OpenClawHandshakeError {
            guard case .pairingRequired = error else {
                XCTFail("Unexpected handshake error: \(error)")
                return
            }
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let remaining = try await credentialStore.load(
            deviceID: deviceID,
            role: "operator"
        )
        XCTAssertNil(remaining)
    }

    func testInvalidPolicyIsTypedHandshakeFailureAndDoesNotPersistGrant() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let deviceID = try identity.deviceID
        let credentialStore = InMemoryOpenClawDeviceCredentialStore()
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: credentialStore
        )
        let connection = OpenClawGatewayConnection(
            socket: InvalidPolicyHandshakeSocket(),
            assembler: assembler
        )

        do {
            _ = try await connection.connect(
                appVersion: "0.1.0",
                credentials: .init(bootstrapToken: "bootstrap")
            )
            XCTFail("Expected invalid-policy handshake failure")
        } catch let error as OpenClawHandshakeError {
            XCTAssertEqual(error, .invalidPolicy)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let saved = try await credentialStore.load(
            deviceID: deviceID,
            role: "operator"
        )
        XCTAssertNil(saved)
    }

    func testTransientGatewayErrorPreservesStoredCredential() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let deviceID = try identity.deviceID
        let credentialStore = InMemoryOpenClawDeviceCredentialStore()
        try await credentialStore.save(
            .init(
                deviceID: deviceID,
                role: "operator",
                scopes: ["operator.read"],
                token: "stored"
            )
        )
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: credentialStore
        )
        let connection = OpenClawGatewayConnection(
            socket: RejectingHandshakeSocket(retryAfterMs: 1_000),
            assembler: assembler
        )

        do {
            _ = try await connection.connect(
                appVersion: "0.1.0",
                credentials: .init(bootstrapToken: "bootstrap")
            )
            XCTFail("Expected transient Gateway rejection")
        } catch let error as AWLOpenClawError {
            XCTAssertEqual(
                error,
                .gateway(
                    code: "BUSY",
                    retryable: true,
                    retryAfterMilliseconds: 1_000
                )
            )
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        let remaining = try await credentialStore.load(
            deviceID: deviceID,
            role: "operator"
        )
        XCTAssertEqual(remaining?.token, "stored")
    }


    func testSharedTokenRejectionRetriesOnceWithStoredDeviceGrant() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let deviceID = try identity.deviceID
        let store = InMemoryOpenClawDeviceCredentialStore()
        try await store.save(
            .init(
                deviceID: deviceID,
                role: "operator",
                scopes: ["operator.read"],
                token: "stored-device-token"
            )
        )
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: store
        )
        let socket = DeviceTokenRecoveryHandshakeSocket(secondAttemptSucceeds: true)
        let connection = OpenClawGatewayConnection(socket: socket, assembler: assembler)

        _ = try await connection.connect(
            appVersion: "0.1.0",
            scopes: ["operator.read", "operator.write"],
            credentials: .init(token: "bad-shared-token")
        )

        let frames = await socket.sentFramesSnapshot()
        XCTAssertEqual(frames.count, 2)

        let first = try decodedConnectParams(frames[0])
        XCTAssertEqual(first.auth?.token, "bad-shared-token")
        XCTAssertNil(first.auth?.deviceToken)

        let second = try decodedConnectParams(frames[1])
        XCTAssertNil(second.auth?.token)
        XCTAssertEqual(second.auth?.deviceToken, "stored-device-token")
        XCTAssertEqual(second.scopes, ["operator.read"])
    }

    func testRetryHintWithoutStoredGrantDoesNotReplayConnect() async throws {
        let socket = DeviceTokenRecoveryHandshakeSocket(secondAttemptSucceeds: true)
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler()
        )

        do {
            _ = try await connection.connect(
                appVersion: "0.1.0",
                credentials: .init(token: "bad-shared-token")
            )
            XCTFail("Expected authentication failure")
        } catch let error as AWLOpenClawError {
            XCTAssertEqual(
                error,
                .gateway(
                    code: "AUTH_FAILED",
                    retryable: false,
                    retryAfterMilliseconds: nil
                )
            )
        }

        let sentCount = await socket.sentCount()
        XCTAssertEqual(sentCount, 1)
    }

    func testFailedDeviceTokenRecoveryIsNotRetriedAgain() async throws {
        let identity = OpenClawDeviceIdentity.generate()
        let store = InMemoryOpenClawDeviceCredentialStore()
        try await store.save(
            .init(
                deviceID: try identity.deviceID,
                role: "operator",
                scopes: ["operator.read"],
                token: "stored-device-token"
            )
        )
        let assembler = OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore(identity: identity)
            ),
            credentialStore: store
        )
        let socket = DeviceTokenRecoveryHandshakeSocket(secondAttemptSucceeds: false)
        let connection = OpenClawGatewayConnection(socket: socket, assembler: assembler)

        do {
            _ = try await connection.connect(
                appVersion: "0.1.0",
                credentials: .init(token: "bad-shared-token")
            )
            XCTFail("Expected authentication failure")
        } catch let error as AWLOpenClawError {
            XCTAssertEqual(
                error,
                .gateway(
                    code: "DEVICE_TOKEN_REJECTED",
                    retryable: false,
                    retryAfterMilliseconds: nil
                )
            )
        }

        let sentCount = await socket.sentCount()
        XCTAssertEqual(sentCount, 2)
    }

    private func decodedConnectParams(_ frame: String) throws -> OpenClawConnectParamsDecoded {
        let data = try XCTUnwrap(frame.data(using: .utf8))
        let object = try XCTUnwrap(
            try JSONSerialization.jsonObject(with: data) as? [String: Any]
        )
        let params = try XCTUnwrap(object["params"] as? [String: Any])
        let auth = params["auth"] as? [String: Any]
        return OpenClawConnectParamsDecoded(
            scopes: params["scopes"] as? [String] ?? [],
            auth: auth.map {
                .init(
                    token: $0["token"] as? String,
                    deviceToken: $0["deviceToken"] as? String
                )
            }
        )
    }

}


private struct OpenClawConnectParamsDecoded {
    struct Auth {
        let token: String?
        let deviceToken: String?
    }

    let scopes: [String]
    let auth: Auth?
}

private actor DeviceTokenRecoveryHandshakeSocket: OpenClawWebSocket {
    private let secondAttemptSucceeds: Bool
    private var sentFrames: [String] = []
    private var receiveCount = 0

    init(secondAttemptSucceeds: Bool) {
        self.secondAttemptSucceeds = secondAttemptSucceeds
    }

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        defer { receiveCount += 1 }

        if receiveCount == 0 {
            return #"{"type":"event","event":"connect.challenge","payload":{"nonce":"auth-retry","ts":1737264000000}}"#
        }

        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }

        if receiveCount == 1 {
            return """
            {"type":"res","id":"\(id)","ok":false,"error":{"code":"AUTH_FAILED","message":"shared token rejected","retryable":false,"details":{"code":"TOKEN_MISMATCH","reason":"shared-token-invalid","canRetryWithDeviceToken":true,"recommendedNextStep":"retry_with_device_token"}}}
            """
        }

        if secondAttemptSucceeds {
            return """
            {"type":"res","id":"\(id)","ok":true,"payload":{"type":"hello-ok","protocol":4,"server":{"version":"2026.10","connId":"recovered"},"features":{"methods":[],"events":[]},"auth":{"role":"operator","scopes":["operator.read"],"deviceToken":"stored-device-token"},"policy":{"maxPayload":26214400,"maxBufferedBytes":52428800,"tickIntervalMs":15000}}}
            """
        }

        return """
        {"type":"res","id":"\(id)","ok":false,"error":{"code":"DEVICE_TOKEN_REJECTED","message":"device token rejected","retryable":false}}
        """
    }

    func close() async {}
    func sentCount() -> Int { sentFrames.count }
    func sentFramesSnapshot() -> [String] { sentFrames }
}

private actor AdaptiveHandshakeSocket: OpenClawWebSocket {
    private let challenge: String
    private var sentFrames: [String] = []
    private var receiveCount = 0

    init(challenge: String) {
        self.challenge = challenge
    }

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        defer { receiveCount += 1 }

        if receiveCount == 0 { return challenge }

        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data)
                as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }

        return """
        {"type":"res","id":"\(id)","ok":true,"payload":{
          "type":"hello-ok","protocol":4,
          "server":{"version":"2026.10","connId":"c1"},
          "features":{"methods":["health"],"events":["agent"]},
          "auth":{"role":"operator","scopes":["operator.read","operator.write"]},
          "policy":{"maxPayload":26214400,"maxBufferedBytes":52428800,"tickIntervalMs":15000}
        }}
        """
    }

    func close() async {}
    func sentCount() -> Int { sentFrames.count }
    func sentFramesSnapshot() -> [String] { sentFrames }
}

private actor RejectingHandshakeSocket: OpenClawWebSocket {
    private let retryAfterMs: Int
    private var sentFrames: [String] = []
    private var receiveCount = 0

    init(retryAfterMs: Int) { self.retryAfterMs = retryAfterMs }

    func connect() async {}

    func send(text: String) async throws { sentFrames.append(text) }

    func receive() async throws -> String {
        defer { receiveCount += 1 }
        if receiveCount == 0 {
            return #"{"type":"event","event":"connect.challenge","payload":{"nonce":"abc","ts":1737264000000}}"#
        }
        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }
        return """
        {"type":"res","id":"\(id)","ok":false,"error":{"code":"BUSY","message":"busy","retryable":true,"retryAfterMs":\(retryAfterMs)}}
        """
    }

    func close() async {}
}


private actor PairingRequiredHandshakeSocket: OpenClawWebSocket {
    private var sentFrames: [String] = []
    private var receiveCount = 0

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        defer { receiveCount += 1 }

        if receiveCount == 0 {
            return #"{"type":"event","event":"connect.challenge","payload":{"nonce":"abc","ts":1737264000000}}"#
        }

        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }

        return """
        {"type":"res","id":"\(id)","ok":false,"error":{
          "code":"AUTH_FAILED","message":"pairing required","retryable":false,
          "details":{
            "code":"PAIRING_REQUIRED",
            "requestId":"pair-1",
            "deviceId":"device-1",
            "reason":"grant rejected",
            "recommendedNextStep":"pair again",
            "waitForResolution":true,
            "pauseReconnect":true
          }
        }}
        """
    }

    func close() async {}
}


private actor InvalidPolicyHandshakeSocket: OpenClawWebSocket {
    private var sentFrames: [String] = []
    private var receiveCount = 0

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        defer { receiveCount += 1 }

        if receiveCount == 0 {
            return #"{"type":"event","event":"connect.challenge","payload":{"nonce":"abc","ts":1737264000000}}"#
        }

        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }

        return """
        {"type":"res","id":"\(id)","ok":true,"payload":{
          "type":"hello-ok","protocol":4,
          "server":{"version":"2026.10","connId":"c-invalid-policy"},
          "features":{"methods":[],"events":[]},
          "auth":{"role":"operator","scopes":["operator.read"],"deviceToken":"must-not-persist"},
          "policy":{"maxPayload":4096,"maxBufferedBytes":8192,"tickIntervalMs":\(Int.max)}
        }}
        """
    }

    func close() async {}
}
