import Foundation
import XCTest
@testable import AgentWearLinkOpenClaw

private actor MockOpenClawWebSocket: OpenClawWebSocket {
    private var inbound: [String]
    private(set) var outbound: [String] = []
    private(set) var didConnect = false
    private(set) var didClose = false

    init(inbound: [String]) {
        self.inbound = inbound
    }

    func connect() async { didConnect = true }

    func send(text: String) async throws {
        outbound.append(text)
    }

    func receive() async throws -> String {
        guard !inbound.isEmpty else { throw AWLOpenClawError.disconnected }
        return inbound.removeFirst()
    }

    func close() async { didClose = true }

    func sent() -> [String] { outbound }
    func closed() -> Bool { didClose }
}

final class OpenClawGatewayConnectionTests: XCTestCase {
    private func makeAssembler() -> OpenClawConnectAssembler {
        OpenClawConnectAssembler(
            identityManager: .init(
                store: InMemoryOpenClawDeviceIdentityStore()
            ),
            credentialStore: InMemoryOpenClawDeviceCredentialStore()
        )
    }

    func testChallengeConnectHelloHandshake() async throws {
        let challenge = #"{"type":"event","event":"connect.challenge","payload":{"nonce":"abc","ts":1737264000000}}"#
        let hello = #"{"type":"res","id":"REQUEST_ID","ok":true,"payload":{"type":"hello-ok","protocol":4,"server":{"version":"2026.10","connId":"c1"},"features":{"methods":["health"],"events":["agent"]},"auth":{"role":"operator","scopes":["operator.read","operator.write"]},"policy":{"maxPayload":26214400,"maxBufferedBytes":52428800,"tickIntervalMs":15000}}}"#

        let socket = MockOpenClawWebSocket(inbound: [challenge])
        await socket.connect()

        // Request IDs are generated by the connection, so use a second mock
        // that rewrites the response after observing the outbound connect.
        let adaptive = AdaptiveHandshakeSocket(challenge: challenge)
        let connection = OpenClawGatewayConnection(
            socket: adaptive,
            assembler: makeAssembler()
        )

        let result = try await connection.connect(
            appVersion: "0.1.0",
            credentials: .init(token: "secret")
        )

        XCTAssertEqual(result.protocolVersion, 4)
        XCTAssertEqual(result.server.connId, "c1")
        XCTAssertEqual(await adaptive.sentCount(), 1)
    }

    func testMissingChallengeClosesSocket() async {
        let socket = MockOpenClawWebSocket(
            inbound: [#"{"type":"event","event":"tick","payload":{}}"#]
        )
        let connection = OpenClawGatewayConnection(
            socket: socket,
            assembler: makeAssembler()
        )

        do {
            _ = try await connection.connect(appVersion: "0.1.0")
            XCTFail("Expected handshake failure")
        } catch let error as OpenClawHandshakeError {
            XCTAssertEqual(error, .challengeRequired)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }

        XCTAssertTrue(await socket.closed())
    }
}

private actor AdaptiveHandshakeSocket: OpenClawWebSocket {
    private let challenge: String
    private var sentFrames: [String] = []
    private var receiveCount = 0

    init(challenge: String) {
        self.challenge = challenge
    }

    func connect() async {}

    func send(text: String) async throws {
        sentFrames.append(text)
    }

    func receive() async throws -> String {
        defer { receiveCount += 1 }

        if receiveCount == 0 { return challenge }

        guard let sent = sentFrames.last,
              let data = sent.data(using: .utf8),
              let json = try JSONSerialization.jsonObject(with: data)
                as? [String: Any],
              let id = json["id"] as? String else {
            throw OpenClawFrameError.malformedFrame
        }

        return """
        {"type":"res","id":"\(id)","ok":true,"payload":{
          "type":"hello-ok","protocol":4,
          "server":{"version":"2026.10","connId":"c1"},
          "features":{"methods":["health"],"events":["agent"]},
          "auth":{"role":"operator","scopes":["operator.read","operator.write"]},
          "policy":{"maxPayload":26214400,"maxBufferedBytes":52428800,"tickIntervalMs":15000}
        }}
        """
    }

    func close() async {}
    func sentCount() -> Int { sentFrames.count }
}
